<?php

function simpletest_block_block($op = 'list', $delta = '', $edit = array()) {
 //simpletest_result_get($test_id)
  switch ($op) {
    case 'list':
      $blocks['simpletest'] = array(
        'info'       => t('Simple Test Status'),
      );

      return $blocks;
    break;
   case 'view':
    $block = array(
      'subject' => t('Simple Test Status'),
      'content' => simpletest_block_view(),
    );
    return $block;
   break;
  }
}

function simpletest_block_view() {
  drupal_add_css(drupal_get_path('module', 'simpletest') . '/simpletest.css', 'module');
  $result = db_query("SELECT * FROM {simpletest_results}");
  $output = '';
  while ($r = db_fetch_object($result)) {
    $output .= '<h3>'. $r->test_name .'</h3>';
    $total = $r->pass + $r->fail + $r->exception;
    if($r->pass)
    $output .= '<div style="background-color: green; width: '. floor(($r->pass / $total)*100) .'px">'. $r->pass .'</div>';
    if($r->exception)
    $output .= '<div style="background-color: orange; width: '. floor(($r->exception / $total)*100) .'px">'. $r->exception .'</div>';
    if($r->fail)
    $output .= '<div style="background-color: red; width: '. floor(($r->fail / $total)*100) .'px">'. $r->fail .'</div>';
    $output .= '<hr/>';
//     $output .= print_r($r, 1);
    
  }
  return $output;
}
function simpletest_block_form_alter($form, $form_state, $form_id) {
  if($form_id == 'simpletest_result_form') {

    foreach($form['result']['results'] as $name => $result) {
      db_query("DELETE FROM {simplest_results} WHERE test_name='%s'", $name);
    //    drupal_set_message("$name = " . print_r($result, 1));
      $r->pass = $result['summary']['#pass'];
      $r->fail = $result['summary']['#fail'];
      $r->exception = $result['summary']['#exception'];
      $r->test_name = $name; 
    //    $total = $r->pass + $r->fail + $r->exception;

      drupal_write_record('simpletest_results', $r);
        
    }
  }
}
