<?php

function simpletest_block_block($op = 'list', $delta = '', $edit = array()) {
 //simpletest_result_get($test_id)
  switch ($op) {
    case 'list':
      $blocks['simpletest'] = array(
        'info'       => t('Simple Test Status'),
      );

      return $blocks;
    break;
    case 'view':
      $block = array(
        'subject' => t('Regression Test Status'),
        'content' => simpletest_block_view(),
      );
      return $block;
    break;
    case 'configure':
    break;
  }
}

function simpletest_block_view() {
  drupal_add_css(drupal_get_path('module', 'simpletest') . '/simpletest.css', 'module');
  $result = db_query("SELECT * FROM {simpletest_results} ORDER BY test_name");
  $output = '';
  $rows = array();
  while ($r = db_fetch_object($result)) {
    $output .= '<h3>'. $r->test_name .'</h3>';
    $total = $r->pass + $r->fail + $r->exception;

//    if($r->pass) {
      $rows[] = array(
        '<div style="background-color: green; width: '. floor(($r->pass / $total)*100) .'px">'. '&nbsp;</div>',
        t('!count passes', array('!count' => $r->pass))
      );
//    }

//    if($r->exception) {
      $rows[] = array(
        '<div style="background-color: orange; width: '. floor(($r->exception / $total)*100) .'px">&nbsp;</div>',
        t('!count exceptions', array('!count' => $r->exception))
      );
//    }

//    if($r->fail) {
      $rows[] = array(
        '<div style="background-color: red; width: '. floor(($r->fail / $total)*100) .'px">&nbsp;</div>',
        t('!count failures', array('!count' => $r->fail))
      );
//    }
    $output .= theme('table', array(), $rows);;
    $rows = array();
  }
  return $output; 
}
function simpletest_block_form_alter($form, $form_state, $form_id) {
  if($form_id == 'simpletest_result_form') {

    foreach($form['result']['results'] as $name => $result) {
      db_query("DELETE FROM {simpletest_results} WHERE test_name='%s'", $name);
    //    drupal_set_message("$name = " . print_r($result, 1));
      $r->pass = $result['summary']['#pass'];
      $r->fail = $result['summary']['#fail'];
      $r->exception = $result['summary']['#exception'];
      $r->test_name = $name; 
    //    $total = $r->pass + $r->fail + $r->exception;

      drupal_write_record('simpletest_results', $r);
        
    }
  }
}
